"""removed chemical.rate

Revision ID: 1f0033346a6e
Revises: b3152e233651
Create Date: 2021-10-29 02:04:52.054647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f0033346a6e'
down_revision = 'b3152e233651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemical', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical', sa.Column('rate', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    # ### end Alembic commands ###
