"""re-added field.archived

Revision ID: 201ac39183e1
Revises: f423eb92e5db
Create Date: 2021-11-03 03:32:34.253800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201ac39183e1'
down_revision = 'f423eb92e5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field', 'archived')
    # ### end Alembic commands ###
