"""changed chemical.rate datatype to String(16)

Revision ID: 3886fc778b32
Revises: 1f0033346a6e
Create Date: 2021-10-29 02:06:17.958793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3886fc778b32'
down_revision = '1f0033346a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical', sa.Column('rate', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemical', 'rate')
    # ### end Alembic commands ###
