"""small changes

Revision ID: 474bc8456228
Revises: 539733ad46e9
Create Date: 2021-10-20 21:31:57.664319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474bc8456228'
down_revision = '539733ad46e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('chemical', sa.Column('wind_dir', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemical', 'wind_dir')
    op.drop_column('chemical', 'rate')
    # ### end Alembic commands ###
