"""empty message

Revision ID: 518a8f8d35f5
Revises: 3886fc778b32
Create Date: 2021-11-03 01:17:15.643884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518a8f8d35f5'
down_revision = '3886fc778b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field', 'archived')
    # ### end Alembic commands ###
