"""chemical table

Revision ID: 539733ad46e9
Revises: 4dc25d92851d
Create Date: 2021-10-13 02:22:14.507392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539733ad46e9'
down_revision = '4dc25d92851d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_date_applied'), 'chemical', ['date_applied'], unique=False)
    op.create_index(op.f('ix_chemical_type'), 'chemical', ['type'], unique=False)
    op.create_index(op.f('ix_seed_date_harvested'), 'seed', ['date_harvested'], unique=False)
    op.create_index(op.f('ix_seed_date_seeded'), 'seed', ['date_seeded'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seed_date_seeded'), table_name='seed')
    op.drop_index(op.f('ix_seed_date_harvested'), table_name='seed')
    op.drop_index(op.f('ix_chemical_type'), table_name='chemical')
    op.drop_index(op.f('ix_chemical_date_applied'), table_name='chemical')
    op.drop_table('chemical')
    # ### end Alembic commands ###
