"""field and seed tables

Revision ID: 652fb87b523d
Revises: 9647f2a8402f
Create Date: 2021-10-10 06:03:19.652356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652fb87b523d'
down_revision = '9647f2a8402f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('land_loc', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_number'), 'field', ['number'], unique=True)
    op.create_table('seed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('date_seeded', sa.Date(), nullable=True),
    sa.Column('date_harvested', sa.Date(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed')
    op.drop_index(op.f('ix_field_number'), table_name='field')
    op.drop_table('field')
    # ### end Alembic commands ###
