"""changed chemical.rate datatype from Interger to Numeric, part 2

Revision ID: b3152e233651
Revises: d334d477577c
Create Date: 2021-10-29 01:50:55.889833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3152e233651'
down_revision = 'd334d477577c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical', sa.Column('rate', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemical', 'rate')
    # ### end Alembic commands ###
