"""remove relationship between field and seed tables

Revision ID: ce645d2f4d89
Revises: ff2cb6aeebef
Create Date: 2021-10-10 06:40:49.594998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce645d2f4d89'
down_revision = 'ff2cb6aeebef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('seed_ibfk_1', 'seed', type_='foreignkey')
    op.drop_column('seed', 'field_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seed', sa.Column('field_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('seed_ibfk_1', 'seed', 'field', ['field_id'], ['id'])
    # ### end Alembic commands ###
