"""changed chemical.rate datatype from Interger to Numeric

Revision ID: d334d477577c
Revises: fed3ac4d7aeb
Create Date: 2021-10-29 01:49:10.707936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd334d477577c'
down_revision = 'fed3ac4d7aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemical', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical', sa.Column('rate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
