"""added chemical_type lookup table for chemical.type

Revision ID: fed3ac4d7aeb
Revises: 474bc8456228
Create Date: 2021-10-29 01:35:52.240742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed3ac4d7aeb'
down_revision = '474bc8456228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_chemical_type', table_name='chemical')
    op.create_foreign_key(None, 'chemical', 'chemical_type', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chemical', type_='foreignkey')
    op.create_index('ix_chemical_type', 'chemical', ['type'], unique=False)
    op.drop_table('chemical_type')
    # ### end Alembic commands ###
