"""added bu_yield and comment to seed table

Revision ID: ff2cb6aeebef
Revises: 652fb87b523d
Create Date: 2021-10-10 06:29:05.472675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2cb6aeebef'
down_revision = '652fb87b523d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seed', sa.Column('bu_yield', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('seed', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seed', 'comment')
    op.drop_column('seed', 'bu_yield')
    # ### end Alembic commands ###
